### ISSUE TITLE
Release 1.16.0

### ISSUE THREAD

**Issue by at-wat** [openspur/yp-spur#94]
### bug fixes
- [x] Fix decelerate logic on over speed https://github.com/openspur/yp-spur/issues/87
- [x] Stricten param err check https://github.com/openspur/yp-spur/pull/88
- [x] Fix serial communication error handling https://github.com/openspur/yp-spur/pull/107

### new features
- [x] Receive error status of connected device https://github.com/openspur/yp-spur/pull/89
  - [x] Update motor error ID https://github.com/openspur/yp-spur/pull/93
- [x] Support inverted hall sensor signal https://github.com/openspur/yp-spur/issues/85
- [x] Add encoder denominator parameter https://github.com/openspur/yp-spur/pull/86
  - [x] Fix ENCODER_DENOMINATOR handling to make param units corresponding to hardware #104

**Comment by at-wat** [comment]
test https://github.com/openspur/yp-spur/releases/tag/1.16.0-rc0 on windows

**Comment by at-wat** [comment]
> test https://github.com/openspur/yp-spur/releases/tag/1.16.0-rc0 on windows

bundled ypspur-gui looks broken

**Comment by at-wat** [comment]
ypspur-gui is fixed and ready for releasing
https://github.com/openspur/ypspur-gui/releases/tag/v0.1.1

**Comment by at-wat** [comment]
## TODO
### bloom release
- [ ] kinetic
- [ ] lunar
- [ ] melodic

### post-release test
- [ ] kinetic
- [ ] lunar
- [ ] melodic

**Comment by at-wat** [comment]
http://build.ros.org/job/Lbin_uxv8_uXv8__ypspur__ubuntu_xenial_arm64__binary/
is failing. 
http://build.ros.org/job/Lbin_dsv8_dSv8__ypspur__debian_stretch_arm64__binary/
http://build.ros.org/job/Mbin_ubv8_uBv8__ypspur__ubuntu_bionic_arm64__binary/
http://build.ros.org/job/Lbin_uxhf_uXhf__ypspur__ubuntu_xenial_armhf__binary/
are OK.

```
07:51:56 dh_auto_configure -- -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar"
07:51:57 	mkdir -p obj-aarch64-linux-gnu
07:51:57 	cd obj-aarch64-linux-gnu
07:51:57 	cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_INSTALL_PREFIX=/opt/ros/lunar
07:51:59 -- The C compiler identification is GNU 5.4.0
07:52:00 -- The CXX compiler identification is GNU 5.4.0
07:52:01 -- Check for working C compiler: /usr/lib/ccache/aarch64-linux-gnu-gcc
07:52:03 -- Check for working C compiler: /usr/lib/ccache/aarch64-linux-gnu-gcc -- works
07:52:03 -- Detecting C compiler ABI info
07:52:05 -- Detecting C compiler ABI info - done
07:52:05 -- Detecting C compile features
07:52:11 -- Detecting C compile features - done
07:52:11 -- Check for working CXX compiler: /usr/lib/ccache/aarch64-linux-gnu-g++
07:52:12 -- Check for working CXX compiler: /usr/lib/ccache/aarch64-linux-gnu-g++ -- broken
07:52:12 -- Configuring incomplete, errors occurred!
07:52:12 See also "/tmp/binarydeb/ros-lunar-ypspur-1.16.0/obj-aarch64-linux-gnu/CMakeFiles/CMakeOutput.log".
07:52:12 See also "/tmp/binarydeb/ros-lunar-ypspur-1.16.0/obj-aarch64-linux-gnu/CMakeFiles/CMakeError.log".
07:52:12 CMake Error at /usr/share/cmake-3.5/Modules/CMakeTestCXXCompiler.cmake:54 (message):
07:52:12   The C++ compiler "/usr/lib/ccache/aarch64-linux-gnu-g++" is not able to
07:52:12   compile a simple test program.
```
seems to be a buildfarm problem?

**Comment by at-wat** [comment]
http://build.ros.org/job/Lbin_uxv8_uXv8__ypspur__ubuntu_xenial_arm64__binary/ gets stable state

**Comment by at-wat** [comment]
post-release tested by using https://github.com/openspur/ypspur_ros/pull/58
